const SET_BOOKABLE_INDEX = 'SET_BOOKABLE_INDEX';
const SET_GROUP = 'SET_GROUP';
const SET_NEXT_BOOKABLE_INDEX = 'SET_NEXT_BOOKABLE_INDEX';
const TOGGLE_BOOKABLE_DETAILS = 'TOGGLE_BOOKABLE_DETAILS';
const FETCH_BOOKABLES_REQUEST = 'FETCH_BOOKABLES_REQUEST';
const FETCH_BOOKABLES_SUCCESS = 'FETCH_BOOKABLES_SUCCESS';
const FETCH_BOOKABLES_ERROR = 'FETCH_BOOKABLES_ERROR';

export { SET_BOOKABLE_INDEX, SET_GROUP, SET_NEXT_BOOKABLE_INDEX, TOGGLE_BOOKABLE_DETAILS, FETCH_BOOKABLES_REQUEST, FETCH_BOOKABLES_SUCCESS, FETCH_BOOKABLES_ERROR };