const SET_BOOKABLE_INDEX = 'SET_BOOKABLE_INDEX';
const SET_GROUP = 'SET_GROUP';
const SET_NEXT_BOOKABLE = 'SET_NEXT_BOOKABLE';
const TOGGLE_BOOKABLE_DETAILS = 'TOGGLE_BOOKABLE_DETAILS';

export { SET_BOOKABLE_INDEX, SET_GROUP, SET_NEXT_BOOKABLE, TOGGLE_BOOKABLE_DETAILS };